[icons]
telegram = ""
firefox = ""
Alacritty = ""
#Termite = ""
gpick = "󰴱"
#Nautilus = "📘"
# smile emoji
#MyNiceProgram = "😛"
nemo = ""
xfceterm = ""
chrome = ""
code = "󰨞"
subl = ""
rustdesk = ""
anydesk = ""
brave = "󰇧"
virtm = ""
discord = "󰙯"
calc = ""
gimp = ""
steam = ""
thunderbird = ""
zathura = ""
stfloat = ""
notify = ""
themes = ""
keepass = ""
gdisk = ""
calculator = "󰃬"
obsidian = ""
draw = "󱦹"
ssh = "󰣀"
qt5ct = ""
rpimg = ""
mpv = ""
nvr = ""
nvim = ""
fontm = ""
fileroller = ""
feh = ""
bluetooth= ""
protonvpn= ""
kitty = "󰄛"
filer = ""
wezterm = ""
dunst = ""
nsxiv = ""
localsend = ""
zed = "🧠"
froller = "🗜"
zen = "󰰸" 
#zen = ""
librestart=""
drawnst=""
zenity=""
writer=""
bottles = "󱄲"

#[aliases.instance]
#"realmonitor" = "nvr"
#"ssh" = "ssh"
#"nvim" = "nvim"

[aliases.class]
"TelegramDesktop" = "telegram"
"Org\\.gnome\\.Nautilus" = "nautilus"
"libreoffice-calc" = "calc"
"libreoffice-draw" = "draw"
"libreoffice-writer" = "writer"
"Firefox" = "firefox"
"Google-chrome-unstable" = "chrome-dev"
"Google-chrome" = "chrome"
"Gimp-\\d\\.\\d\\d" = "gimp"
"^discord$" = "discord"
"Steam" = "steam"
"Thunderbird" = "thunderbird"
"Xfce4-terminal" = "xfceterm"
"Nemo" = "nemo"
"Brave-browser" = "brave"
"Virt-manager" = "virtm"
"org\\.pwmt\\.zathura" = "zathura"
"Zathura" = "zathura"
"St" = "stfloat"
#"drawn-st" = "stfloat"
"Subl" = "subl"
"code-oss" = "code"
"Xfce4-notifyd" = "notify"
"Rustdesk" = "rustdesk"
"Anydesk" = "anydesk"
"Lxappearance" = "themes"
"KeePassXC" = "keepass"
"Gnome-disks" = "gdisk"
"Mate-calc" = "calculator"
"obsidian" = "obsidian"
"qt5ct" = "qt5ct"
"Imager" = "rpimg"
"mpv" = "mpv"
"Font-manager" = "fontm"
"File-roller" = "fileroller"
"feh" = "feh"
"blueman-manager" = "bluetooth"
"Alacritty" = "Alacritty"
"Protonvpn" = "protonvpn"
"kitty" = "kitty"
"file\\.roller" = "filer"
"org\\.wezfurlong\\.wezterm" = "wezterm"
"Dunst" = "dunst"
"nsxiv" = "nsxiv"
"localsend" = "localsend"
"dev\\.zed\\.Zed" = "zed"
"file-roller" = "froller"
"zen-beta" = "zen"
"libreoffice-startcenter" = "librestart"
"drawn-st" = "drawnst"
"zenity" = "zenity"
"Bottles" = "bottles"

[general]
#separator = " "
#default_icon = ""
default_icon = "💀"
separator = "·"
wm_property = "class"

[options]
remove_duplicates = false
no_names = true
no_icon_names = false
