#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#


#
# Variables
#

# QT env Variables for xdpi and for qt5ct

export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1
export QT_SELECT=5
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

export GTK_THEME=Nordic-darker

#
# Editors
#

# export EDITOR='nano'
# export VISUAL='nano'
# export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
## if [ -d "$HOME/.local/bin" ] ; then
##     PATH="$HOME/.local/bin:$PATH"
## fi

# Ensure path arrays do not contain duplicates. removed -U option invalid
typeset -g cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# PATHs

dirs=(
  '/bin'
  '/sbin'
  '/usr/bin'
  '/usr/sbin'
  '/usr/local/bin'
  '/usr/local/sbin'
  '/usr/games'
  '/usr/local/games'
  "$HOME/.local/bin"
)

for d in "${dirs[@]}"; do
  if [[ -d "$d" ]]; then
    PATH="$d:$PATH"
  fi
done

export PATH

# Set the list of directories that Zsh searches for programs.
## path=(
##   /usr/local/{bin,sbin}
##   $path
## )

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -X -z-4'
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
### if (( $#commands[(i)lesspipe(|.sh)] )); then
###   export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
### fi


# Set keyboard to US-INTL with accents and deadkey

#setxkbmap -layout latam -variant deadtilde

#
# Hardware Settings
#

# Synaptics Dell Touchpad tweaks

# Enable tap to click
#synclient TapButton1=1

# Enable two-finger touch to left click
#synclient TapButton2=3

# Enable natural scrolling
#synclient VertScrollDelta=-"$(synclient | grep VertScrollDelta | cut -d '=' -f 2 | cut -c 2-)
#synclient HorizScrollDelta=-"$(synclient | grep HorizScrollDelta | cut -d '=' -f 2 | cut -c 2-)

# Enable horizontal scroll with two fingers
#synclient HorizTwoFingerScroll=1
#


