[flavor]
dark = "catppuccin-macchiato"

[icon]
prepend_globs = [
	{ url = "/home/poole/VMs/", text = "\uf108" },
	{ url = "/home/poole/Mega/", text = "\uf0c2" },
]
prepend_dirs = [
	{ name = "Dropbox", text = "\uf16b" },
	{ name = "Comprobantes", text = "\uf0ba" },
	{ name = "Projects", text = "\uf121" },
]
